### PR TITLE
Cabal: use build-tool-depends

### PR DESCRIPTION
**Pull request by domenkozar**
Supersedes #10 

cc @sol

### CODE REVIEW

**Comment by domenkozar** [comment]
Seems to be added in Cabal 2.0, so it's not clear to me why tests fail: https://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-build-tool-depends

**Comment by domenkozar** [comment]
I would have hoped that Cabal would do the right thing here:

```
$ cd example && cabal install --only-dependencies --enable-tests && cabal configure --enable-tests && cabal build && cabal test
Resolving dependencies...
All the requested packages are already installed:
Use --reinstall if you want to reinstall anyway.
Resolving dependencies...
Configuring nifty-library-0.0.0...
Preprocessing test suite 'readme' for nifty-library-0.0.0..
Building test suite 'readme' for nifty-library-0.0.0..
ghc: could not execute: markdown-unlit
```

**Comment by domenkozar** [comment]
@sol this should now support old and new Cabal builds. I've struggled with this quite a bit, hopefully it can save others time in the future.

**Comment by buggymcbugfix** [comment]
Any plans to merge this?

**Comment by domenkozar** [comment]
@sol any feedback?

**Comment by domenkozar** [comment]
Please?

**Comment by sol** [comment]
@domenkozar thanks a lot for the PR + sorry for the unacceptable delay on this.

**Pull request merged**
