### PR TITLE
Readme fix. Only indented blocks are a limitation

### PR DESCRIPTION
**Pull request by simon-nicholls**
I tried to use different fencing for my code, and it worked anyway. Having viewed the recent commits, I've now removed the fencing and class bracketing limitations from the Readme.

### CODE REVIEW

**Comment by soenkehahn** [comment]
@sol: Can you merge this, please? (Great, that this works now, btw.)

**Comment by sol** [comment]
@simon-nicholls Thanks a lot for the readme update, and sorry for the delay.

**Comment by simon-nicholls** [comment]
No worries, and thanks for the project; very handy.

**Comment by soenkehahn** [comment]
Thanks, both of you!

**Pull request merged**
